
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import "./layout.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="menu">
          <ul>
            {/* <li><Link href="/login">Войти в кабинет</Link></li> */}
            <Link href="/"><li className="menu_top"><img src={'/images/logo.svg'}  className="menu_svg_top"/><span className="fat_grot_span">СПОРТ ТЕХ</span></li></Link>
            
            <Link href="/login" id="login"><li className="menu_bot"><img src={"/images/user.png"}/>Войти в кабинет</li></Link>
            <span className="break_line"></span>
            <Link href="/articles"><li id="articles"><img id="book_icon" src={"/images/book.svg"} className="menu_svg"/>Статьи</li></Link>
            
            <Link href="/map"><li id="map"><img id="map_icon" src={'/images/map.svg'}  className="menu_svg"/>Карта</li></Link>
        
            <Link href="/competitions"><li id="competitions"><img  id="comp_icon" src={'/images/competitions.svg'} className="menu_svg"/>События</li></Link>
        
            <Link href="/ratings"><li id="ratings"><img  src={'/images/cup.svg'} id="rating_icon" className="menu_svg"/>Рейтинг</li></Link>
            

            
          </ul>
        </div>

        {children}
      </body>
    </html>
  );
}
